maintainer "Tobias Wilken"
maintainer_email "tw@cloudcontrol.de"
license "Apache 2.0"
description "Installs and configures serverdensity"
version "0.1.2"
depends "apt"
recipe "serverdensity::default", "Downloads, install and configures serverdensity"
