default[:serverdensity][:mongodb_server] = ''
default[:serverdensity][:mongodb_dbstats] = 'no'
default[:serverdensity][:mongodb_replset] = 'no'
default[:serverdensity][:nginx_status_url] = 'http://www.example.com/nginx_status'
default[:serverdensity][:plugin_directory] = '/etc/sd-agent/plugins'
